---

- name: Configure sudoers
  template:
    src: sudoers.cvmfs.j2
    dest: /etc/sudoers.d/80-cvmfs-sudoers
    owner: root
    group: root
    mode: "u=r,g=r,o="
    validate: '/usr/sbin/visudo -c -f %s'
  vars:
    cvmfs_sudoers: "{{ cvmfs_admin_list.keys()|intersect(cvmfs_authorized_admins) }}"
  when: cvmfs_sudoers | length > 0
