---

- name: Install CVMFS gateway RPM (stratum 0)
  yum: name="cvmfs-gateway"

# The template or copy (using the src parameter) modules would work well here,
# but unfortunately they do not support the state parameter: https://github.com/ansible/ansible/issues/29781
# So, a combination of template and file is used instead. In fact, they work well together for the following reason.
# We require 'force: no' so that the API keys are only generated once, when they don't already exist.
# A limitation of this is that if the file properties change (i.e. chmod) they won't get corrected.
# So, using the file module after the template module addresses this limitation, and also correctly applies 
# negative configuration via the state parameter according to the gateway variable.

- name: Create gateway API keys for repository publishing access (stratum 0)
  template:
    src: repokey.gw.j2
    dest: "/etc/cvmfs/keys/{{ item.key }}.gw"
    force: no
    owner: root
    group: root
    mode: '400'
  vars:
    cvmfs_repo_name: "{{ item.key }}"
    cvmfs_gateway_key: "{{ lookup('password', '/dev/null chars=ascii_letters,digits') }}" 
  with_dict: "{{ cvmfs_repo_list }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.value.gateway|default(false)
  notify: "restart cvmfs-gateway"

- name: Set properties of gateway API keys (stratum 0)
  file:
    path: "/etc/cvmfs/keys/{{ item.key }}.gw"
    owner: root
    group: root
    mode: '400'
    state: "{{ 'file' if (item.value.gateway|default(false)) else 'absent' }}"
  with_dict: "{{ cvmfs_repo_list }}"
  loop_control:
    label: "{{ item.key }}"
  notify: "restart cvmfs-gateway"

# The public repo keys (.crt, .pub) and shared secret API key (.gw) are needed
# on the publisher node, so for each repo put them all in a tar file for convenience.
- name: Bundle up gateway API keys in /tmp/ for manual transportation (stratum 0)
  archive:
    dest: "/tmp/keys-{{ item.key }}.tar"
    format: "tar"
    owner: root
    group: root
    mode: '400'
    path:
      - "/etc/cvmfs/keys/{{ item.key }}.gw"
      - "/etc/cvmfs/keys/{{ item.key }}.crt"
      - "/etc/cvmfs/keys/{{ item.key }}.pub"
    remove: no
  with_dict: "{{ cvmfs_repo_list }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.value.gateway|default(false)

# TODO what about the user.json and repo.json files? Configure by hand or ...?

- name: Enable gateway service (stratum 0)
  service:
    name: cvmfs-gateway
    enabled: yes
    state: started

