---

- name: Disable automatic garbage collection
  lineinfile:
    dest: "/etc/cvmfs/repositories.d/{{ item }}/server.conf"
    regexp: "^CVMFS_AUTO_GC"
    state: absent
  with_items: "{{ cvmfs_repo_list }}"

- name: Create cron task for garbage collection
  cron: name="cvmfs-garbage-collection all" cron_file="cvmfs-garbage-collection" user="root" minute="00" hour="02" job="/usr/bin/cvmfs_server gc -a -l -f"
