---

- name: Check for iptables line marker
  lineinfile:
    path: /etc/sysconfig/iptables
    line: "# INSERT CVMFS RULES HERE"
  check_mode: true
  register: iptables_line_marker

# Unaesthetic but unavoidable. See 20170922 minutes.
- name: Fail if iptables line marker is absent
  fail: msg="Please manually insert the line marker string '# INSERT CVMFS RULES HERE' at the appropriate position in the iptables file."
  when: iptables_line_marker.changed

# map extract requires python-jinja2 >= 2.7, so we need to skip this for now on EL6 hosts. 
# TODO: clean up after EL6 hosts are gone, just use a var: in the following blockinfile

- set_fact:
    cvmfs_login_acl: "{{ cvmfs_authorized_admins | map('extract', cvmfs_admin_list, 'login') | flatten | unique }}"
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Scientific"
    - ansible_distribution_major_version is version_compare("7", ">=")

- name: Apply CVMFS iptables rules
  blockinfile:
    marker: "# --- {mark} Ansible managed for CVMFS"
    insertafter: "^# INSERT CVMFS RULES HERE" 
    state: present
    dest: /etc/sysconfig/iptables
    block: "{{ lookup('template', 'templates/iptables.cvmfs.j2') }}"

# don't use a handler because we're uninstalling firewalld next,
# so iptables needs to be activated before that for continuous protection.
- name: Enable and reload iptables rules
  service: name=iptables enabled=yes state=reloaded
  changed_when: false

- name: Uninstall firewalld
  yum: name=firewalld state=absent
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Scientific"
    - ansible_distribution_major_version is version_compare("7", ">=")

#- name: reload ip6tables rules
#  service: name=ip6tables state=reloaded
