---

# This task should contain all configuration actions that pertain to individual repositories (including repository creation and replication), except gateway-specific steps.

# Stratum 1 tasks
- name: Install CVMFS repository keys (stratum 1)
  copy: src="{{ item.name }}.pub" dest="/etc/cvmfs/keys/{{ item.name }}.pub" mode=0444 owner=root group=root
  loop: "{{ cvmfs_repo_list }}"
  loop_control:
    label: "{{ item.name }}"
  when: 
    - cvmfs_stratum_level == "stratum1"
    - item.replicate | default(true)

# On s1, repo ownership does not matter in the same way as on s0, so we always use the unprivileged cvmfs service account.
- name: Adding repository replicas (stratum 1)
  command:
    cmd: cvmfs_server add-replica -o cvmfs -w http://localhost:{{ cvmfs_http_port }}/cvmfs/{{ item.name }} {{ item.server_url | default(default_url) }} /etc/cvmfs/keys/
    creates: "/etc/cvmfs/repositories.d/{{ item.name }}/server.conf"
  vars:
    default_url: "http://{{ item.cvmfs_s0_address | default(cvmfs_s0_address) }}/cvmfs/{{ item.name }}"
  loop: "{{ cvmfs_repo_list }}"
  loop_control:
    label: "{{ item.name }}"
  when: 
    - cvmfs_stratum_level == "stratum1"
    - item.replicate | default(true)

# increase timeouts and retries to avoid "serving data too slowly" errors
# Changing the same file twice sucks, but safer than overwriting with a template.
# Could use a looping include with a big refactoring though.
- name: Modify replica.conf timeouts (stratum 1)
  lineinfile:
    path: "/etc/cvmfs/repositories.d/{{ item.name }}/replica.conf"
    regexp: '^CVMFS_HTTP_TIMEOUT'
    line: "CVMFS_HTTP_TIMEOUT=30"
  loop: "{{ cvmfs_repo_list }}"
  loop_control:
    label: "{{ item.name }}"
  when: 
    - cvmfs_stratum_level == "stratum1"
    - item.replicate | default(true)

- name: Modify replica.conf retries (stratum 1)
  lineinfile:
    path: "/etc/cvmfs/repositories.d/{{ item.name }}/replica.conf"
    regexp: '^CVMFS_HTTP_RETRIES'
    line: "CVMFS_HTTP_RETRIES=5"
  loop: "{{ cvmfs_repo_list }}"
  loop_control:
    label: "{{ item.name }}"
  when: 
    - cvmfs_stratum_level == "stratum1"
    - item.replicate | default(true)

# Stratum 0 tasks
- name: Create cvmfs-whitelist-check script (stratum 0)
  template:
    src: cvmfs-whitelist-check.j2
    dest: /usr/local/bin/cvmfs-whitelist-check
    owner: root
    group: root
    mode: 0755
  when:
    - cvmfs_stratum_level == "stratum0"
    - institute == "uvic"

# Use template instead of cron, to apply negative configuration when a repo is removed.
# Monitoring is done via UVic syslog message processing and alerting system
- name: Create cron jobs to check whitelists (stratum 0)
  template:
    src: cvmfs-whitelist-check.cron.j2
    dest: /etc/cron.d/cvmfs-whitelist-check
    owner: root
    group: root
    mode: 0644
  when:
    - cvmfs_stratum_level == "stratum0"
    - institute == "uvic"

- name: Create cron jobs to re-sign whitelists (stratum 0)
  template:
    src: cvmfs-whitelist-resign.cron.j2
    dest: /etc/cron.d/cvmfs-whitelist-resign
    owner: root
    group: root
    mode: 0644
  when: cvmfs_stratum_level == "stratum0"

# Using the gateway, the repo owner does not matter on the s0 either. 
- name: Please run the following commands manually now to create repositories (stratum 0)
  debug: msg="cvmfs_server mkfs -w {{ item.server_url | default(default_url) }} {{ item.options | default('') }} {{ standard_options }} {{ item.name }}"
  vars:
    default_url: "http://localhost:{{ cvmfs_http_port }}/cvmfs/{{ item.name }}"
    standard_options: "-o cvmfs -f overlayfs -G '30 days ago' -a shake128 -z"
  loop: "{{ cvmfs_repo_list }}"
  when: cvmfs_stratum_level == "stratum0"
  loop_control:
    label: "{{ item.name }}"

# Stratum 0 and 1 tasks

# Apply some configuration to repository server.conf.
# Should only be used for settings that are not otherwise already present by default in server.conf .
- name: Apply repository configuration
  blockinfile:
    marker: "# --- {mark} Ansible managed for CVMFS"
    insertafter: EOF
    state: present
    dest: "/etc/cvmfs/repositories.d/{{ item.name }}/server.conf"
    block: "{{ lookup('template', 'templates/server.conf.j2') }}"
  vars:
    cvmfs_server_conf: "{{ item.server_conf | default({}) }}"
  loop: "{{ cvmfs_repo_list }}"
  when: (cvmfs_stratum_level == "stratum0") or (cvmfs_stratum_level == "stratum1" and (item.replicate | default(true)))
  loop_control:
    label: "{{ item.name }}"

# The -z option used in repo creation sets up both 'CVMFS_GARBAGE_COLLECTION=true' and 'CVMFS_AUTO_GC=true', but we only want the former.
- name: Disable repository-level automatic garbage collection
  lineinfile:
    dest: "/etc/cvmfs/repositories.d/{{ item.name }}/server.conf"
    regexp: "^CVMFS_AUTO_GC"
    state: absent
  loop: "{{ cvmfs_repo_list }}"

